### ISSUE TITLE
useLocalStorage 반환 타입 질문

### ISSUE THREAD

**Issue by hyseoseo** [freeonboard-highfive/Assignment8-TeamB#7]
**버그 설명**
버그는 아니지만 모든 개발 진행상황을 최대한 이슈에서 공유하는 것을 목표로 하기 위해 useLocalStorage hook 사용에 대한 질문을 여기에 드립니다!

**재현하려면**
useLocalStorage를 아래와 같이 사용하였습니다. 

const initialTodolist: Itodo[] = [];

export const useTodo = () => {
  const [todos, setTodos] = useLocalStorage(
    STORAGE_KEYS.todos,
    initialTodolist
  );

 ...

이 때 todos의 type을 콘솔에 출력하면 Object가 나오고, 따라서 map, filter, concat 등 배열 메소드를 사용할 수 없다고 나옵니다. Itodo[] type을 파라미터로 전달했는데 왜 배열이 아닌 객체가 리턴되는지 모르겠습니다 ㅠㅠ JSON.parse 결과 타입을 지정해주어야 할까요? (그러나 현재 상황에서는 localStorage가 비어있어서 initialTodoListrk 반환될텐데... 왜 배열이 아닌 객체일까요...???)

**원하는 동작**
useLocalStorage에서 반환되는 value가 Itodo[]이기를 원합니다.

**추가 컨텍스트**
useLocalStorage<null, T>(...)로 작성하여도 Object 타입을 반환합니다.

**Comment by thinkJin6** [comment]
@hyseoseo 희영님 코드 한 번 볼 수 있을까요?! 이렇게 확인했을 때는 타입 잘 들어오네요.
```jsx
interface Itodo {
  id: string;
  task: string;
}
const initialValue: Itodo[] = [];

const todo: Itodo = {
  id: '1',
  task: 'hey',
};

const TodoContainer: React.FC = () => {
  const [todos, setTodos] = useLocalStorage(STORAGE_KEYS.todos, initialValue);

  const handleClick = () => {
    setTodos([...todos, todo]);
    console.log(todos);
  };

  return (
    <div css={TodoTemplate} onClick={handleClick}>
      <TodoHead />
      <TodoList />
    </div>
  );
};
```

**Comment by hyseoseo** [comment]
> @hyseoseo 희영님 코드 한 번 볼 수 있을까요?! 이렇게 확인했을 때는 타입 잘 들어오네요.
> 
> ```js
> interface Itodo {
>   id: string;
>   task: string;
> }
> const initialValue: Itodo[] = [];
> 
> const todo: Itodo = {
>   id: '1',
>   task: 'hey',
> };
> 
> const TodoContainer: React.FC = () => {
>   const [todos, setTodos] = useLocalStorage(STORAGE_KEYS.todos, initialValue);
> 
>   const handleClick = () => {
>     setTodos([...todos, todo]);
>     console.log(todos);
>   };
> 
>   return (
>     <div css={TodoTemplate} onClick={handleClick}>
>       <TodoHead />
>       <TodoList />
>     </div>
>   );
> };
> ```

오! 감사합니다. 해결됐습니다. 기존 코드는 이러했는데요

```javascript
const removeTodo = (id: number): void => {
    setTodos((prevState) => prevState.filter((todo: Itodo) => todo.id !== id));
  };
```
올려주신 것처럼 스프레드 하니까 잘 들어갑니다! 

```javascript
const removeTodo = (id: number): void => {
   const prev = [...todos];
    setTodos(prev.filter((todo: Itodo) => todo.id !== id));
  };
```

**Comment by thinkJin6** [comment]
@hyseoseo 
이렇게 해도 혹시 오류가 날까요? 어떤게 문제였는지 찾고 싶어서요!
```tsx
const removeTodo = (id: number): void => {
    const newTodos = todos.filter((todo: Itodo) => todo.id !== id);
    setTodos(newTodos);
}
```

**Comment by hyseoseo** [comment]
> @hyseoseo
> 이렇게 해도 혹시 오류가 날까요? 어떤게 문제였는지 찾고 싶어서요!
> 
> ```tsx
> const removeTodo = (id: number): void => {
>     const newTodos = todos.filter((todo: Itodo) => todo.id !== id);
>     setTodos(newTodos);
> }
> ```

이미 해결하셨지만 기록의 차원에서... 이렇게 하면 오류 안 납니다! arrow function이 문제였네요 ㅎㅎ
